#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixApp.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FirstAppDb")]
	public partial class DbFirstDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblFirma(tblFirma instance);
    partial void UpdatetblFirma(tblFirma instance);
    partial void DeletetblFirma(tblFirma instance);
    partial void InserttblKategoriler(tblKategoriler instance);
    partial void UpdatetblKategoriler(tblKategoriler instance);
    partial void DeletetblKategoriler(tblKategoriler instance);
    partial void InserttblMarkalar(tblMarkalar instance);
    partial void UpdatetblMarkalar(tblMarkalar instance);
    partial void DeletetblMarkalar(tblMarkalar instance);
    partial void InserttblStokDurum(tblStokDurum instance);
    partial void UpdatetblStokDurum(tblStokDurum instance);
    partial void DeletetblStokDurum(tblStokDurum instance);
    partial void InserttblStokGirisAlt(tblStokGirisAlt instance);
    partial void UpdatetblStokGirisAlt(tblStokGirisAlt instance);
    partial void DeletetblStokGirisAlt(tblStokGirisAlt instance);
    partial void InserttblStokGirisUst(tblStokGirisUst instance);
    partial void UpdatetblStokGirisUst(tblStokGirisUst instance);
    partial void DeletetblStokGirisUst(tblStokGirisUst instance);
    partial void InserttblSiparisUst(tblSiparisUst instance);
    partial void UpdatetblSiparisUst(tblSiparisUst instance);
    partial void DeletetblSiparisUst(tblSiparisUst instance);
    partial void InserttblSiparisAlt(tblSiparisAlt instance);
    partial void UpdatetblSiparisAlt(tblSiparisAlt instance);
    partial void DeletetblSiparisAlt(tblSiparisAlt instance);
    partial void InserttblUrunler(tblUrunler instance);
    partial void UpdatetblUrunler(tblUrunler instance);
    partial void DeletetblUrunler(tblUrunler instance);
    #endregion
		
		public DbFirstDataContext() : 
				base(global::MixApp.Properties.Settings.Default.FirstAppDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbFirstDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbFirstDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbFirstDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbFirstDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblFirma> tblFirmas
		{
			get
			{
				return this.GetTable<tblFirma>();
			}
		}
		
		public System.Data.Linq.Table<tblKategoriler> tblKategorilers
		{
			get
			{
				return this.GetTable<tblKategoriler>();
			}
		}
		
		public System.Data.Linq.Table<tblMarkalar> tblMarkalars
		{
			get
			{
				return this.GetTable<tblMarkalar>();
			}
		}
		
		public System.Data.Linq.Table<tblStokDurum> tblStokDurums
		{
			get
			{
				return this.GetTable<tblStokDurum>();
			}
		}
		
		public System.Data.Linq.Table<tblStokGirisAlt> tblStokGirisAlts
		{
			get
			{
				return this.GetTable<tblStokGirisAlt>();
			}
		}
		
		public System.Data.Linq.Table<tblStokGirisUst> tblStokGirisUsts
		{
			get
			{
				return this.GetTable<tblStokGirisUst>();
			}
		}
		
		public System.Data.Linq.Table<tblSiparisUst> tblSiparisUsts
		{
			get
			{
				return this.GetTable<tblSiparisUst>();
			}
		}
		
		public System.Data.Linq.Table<vwStokGiri> vwStokGiris
		{
			get
			{
				return this.GetTable<vwStokGiri>();
			}
		}
		
		public System.Data.Linq.Table<vwSiparisAl> vwSiparisAls
		{
			get
			{
				return this.GetTable<vwSiparisAl>();
			}
		}
		
		public System.Data.Linq.Table<tblSiparisAlt> tblSiparisAlts
		{
			get
			{
				return this.GetTable<tblSiparisAlt>();
			}
		}
		
		public System.Data.Linq.Table<tblUrunler> tblUrunlers
		{
			get
			{
				return this.GetTable<tblUrunler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFirma")]
	public partial class tblFirma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CariKod;
		
		private string _FirmaAdi;
		
		private string _Adres;
		
		private string _Yetkili;
		
		private string _Departman;
		
		private string _eMail;
		
		private string _Telefon;
		
		private string _GSM;
		
		private string _Faks;
		
		private string _VergiD;
		
		private string _VergiN;
		
		private EntitySet<tblStokGirisUst> _tblStokGirisUsts;
		
		private EntitySet<tblSiparisUst> _tblSiparisUsts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCariKodChanging(string value);
    partial void OnCariKodChanged();
    partial void OnFirmaAdiChanging(string value);
    partial void OnFirmaAdiChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnYetkiliChanging(string value);
    partial void OnYetkiliChanged();
    partial void OnDepartmanChanging(string value);
    partial void OnDepartmanChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnGSMChanging(string value);
    partial void OnGSMChanged();
    partial void OnFaksChanging(string value);
    partial void OnFaksChanged();
    partial void OnVergiDChanging(string value);
    partial void OnVergiDChanged();
    partial void OnVergiNChanging(string value);
    partial void OnVergiNChanged();
    #endregion
		
		public tblFirma()
		{
			this._tblStokGirisUsts = new EntitySet<tblStokGirisUst>(new Action<tblStokGirisUst>(this.attach_tblStokGirisUsts), new Action<tblStokGirisUst>(this.detach_tblStokGirisUsts));
			this._tblSiparisUsts = new EntitySet<tblSiparisUst>(new Action<tblSiparisUst>(this.attach_tblSiparisUsts), new Action<tblSiparisUst>(this.detach_tblSiparisUsts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariKod", DbType="NVarChar(50)")]
		public string CariKod
		{
			get
			{
				return this._CariKod;
			}
			set
			{
				if ((this._CariKod != value))
				{
					this.OnCariKodChanging(value);
					this.SendPropertyChanging();
					this._CariKod = value;
					this.SendPropertyChanged("CariKod");
					this.OnCariKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdi", DbType="NVarChar(350)")]
		public string FirmaAdi
		{
			get
			{
				return this._FirmaAdi;
			}
			set
			{
				if ((this._FirmaAdi != value))
				{
					this.OnFirmaAdiChanging(value);
					this.SendPropertyChanging();
					this._FirmaAdi = value;
					this.SendPropertyChanged("FirmaAdi");
					this.OnFirmaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(450)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetkili", DbType="NVarChar(100)")]
		public string Yetkili
		{
			get
			{
				return this._Yetkili;
			}
			set
			{
				if ((this._Yetkili != value))
				{
					this.OnYetkiliChanging(value);
					this.SendPropertyChanging();
					this._Yetkili = value;
					this.SendPropertyChanged("Yetkili");
					this.OnYetkiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departman", DbType="NVarChar(50)")]
		public string Departman
		{
			get
			{
				return this._Departman;
			}
			set
			{
				if ((this._Departman != value))
				{
					this.OnDepartmanChanging(value);
					this.SendPropertyChanging();
					this._Departman = value;
					this.SendPropertyChanged("Departman");
					this.OnDepartmanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(50)")]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(20)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSM", DbType="NVarChar(20)")]
		public string GSM
		{
			get
			{
				return this._GSM;
			}
			set
			{
				if ((this._GSM != value))
				{
					this.OnGSMChanging(value);
					this.SendPropertyChanging();
					this._GSM = value;
					this.SendPropertyChanged("GSM");
					this.OnGSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faks", DbType="NVarChar(20)")]
		public string Faks
		{
			get
			{
				return this._Faks;
			}
			set
			{
				if ((this._Faks != value))
				{
					this.OnFaksChanging(value);
					this.SendPropertyChanging();
					this._Faks = value;
					this.SendPropertyChanged("Faks");
					this.OnFaksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiD", DbType="NVarChar(50)")]
		public string VergiD
		{
			get
			{
				return this._VergiD;
			}
			set
			{
				if ((this._VergiD != value))
				{
					this.OnVergiDChanging(value);
					this.SendPropertyChanging();
					this._VergiD = value;
					this.SendPropertyChanged("VergiD");
					this.OnVergiDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiN", DbType="NVarChar(20)")]
		public string VergiN
		{
			get
			{
				return this._VergiN;
			}
			set
			{
				if ((this._VergiN != value))
				{
					this.OnVergiNChanging(value);
					this.SendPropertyChanging();
					this._VergiN = value;
					this.SendPropertyChanged("VergiN");
					this.OnVergiNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFirma_tblStokGirisUst", Storage="_tblStokGirisUsts", ThisKey="ID", OtherKey="FirmaID")]
		public EntitySet<tblStokGirisUst> tblStokGirisUsts
		{
			get
			{
				return this._tblStokGirisUsts;
			}
			set
			{
				this._tblStokGirisUsts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFirma_tblSiparisUst", Storage="_tblSiparisUsts", ThisKey="ID", OtherKey="FirmaID")]
		public EntitySet<tblSiparisUst> tblSiparisUsts
		{
			get
			{
				return this._tblSiparisUsts;
			}
			set
			{
				this._tblSiparisUsts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblStokGirisUsts(tblStokGirisUst entity)
		{
			this.SendPropertyChanging();
			entity.tblFirma = this;
		}
		
		private void detach_tblStokGirisUsts(tblStokGirisUst entity)
		{
			this.SendPropertyChanging();
			entity.tblFirma = null;
		}
		
		private void attach_tblSiparisUsts(tblSiparisUst entity)
		{
			this.SendPropertyChanging();
			entity.tblFirma = this;
		}
		
		private void detach_tblSiparisUsts(tblSiparisUst entity)
		{
			this.SendPropertyChanging();
			entity.tblFirma = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKategoriler")]
	public partial class tblKategoriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KategoriAdi;
		
		private EntitySet<tblUrunler> _tblUrunlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKategoriAdiChanging(string value);
    partial void OnKategoriAdiChanged();
    #endregion
		
		public tblKategoriler()
		{
			this._tblUrunlers = new EntitySet<tblUrunler>(new Action<tblUrunler>(this.attach_tblUrunlers), new Action<tblUrunler>(this.detach_tblUrunlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriAdi", DbType="NVarChar(100)")]
		public string KategoriAdi
		{
			get
			{
				return this._KategoriAdi;
			}
			set
			{
				if ((this._KategoriAdi != value))
				{
					this.OnKategoriAdiChanging(value);
					this.SendPropertyChanging();
					this._KategoriAdi = value;
					this.SendPropertyChanged("KategoriAdi");
					this.OnKategoriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKategoriler_tblUrunler", Storage="_tblUrunlers", ThisKey="ID", OtherKey="KategoriID")]
		public EntitySet<tblUrunler> tblUrunlers
		{
			get
			{
				return this._tblUrunlers;
			}
			set
			{
				this._tblUrunlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUrunlers(tblUrunler entity)
		{
			this.SendPropertyChanging();
			entity.tblKategoriler = this;
		}
		
		private void detach_tblUrunlers(tblUrunler entity)
		{
			this.SendPropertyChanging();
			entity.tblKategoriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMarkalar")]
	public partial class tblMarkalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MarkaAdi;
		
		private EntitySet<tblUrunler> _tblUrunlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMarkaAdiChanging(string value);
    partial void OnMarkaAdiChanged();
    #endregion
		
		public tblMarkalar()
		{
			this._tblUrunlers = new EntitySet<tblUrunler>(new Action<tblUrunler>(this.attach_tblUrunlers), new Action<tblUrunler>(this.detach_tblUrunlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaAdi", DbType="NVarChar(100)")]
		public string MarkaAdi
		{
			get
			{
				return this._MarkaAdi;
			}
			set
			{
				if ((this._MarkaAdi != value))
				{
					this.OnMarkaAdiChanging(value);
					this.SendPropertyChanging();
					this._MarkaAdi = value;
					this.SendPropertyChanged("MarkaAdi");
					this.OnMarkaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMarkalar_tblUrunler", Storage="_tblUrunlers", ThisKey="ID", OtherKey="MarkaID")]
		public EntitySet<tblUrunler> tblUrunlers
		{
			get
			{
				return this._tblUrunlers;
			}
			set
			{
				this._tblUrunlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUrunlers(tblUrunler entity)
		{
			this.SendPropertyChanging();
			entity.tblMarkalar = this;
		}
		
		private void detach_tblUrunlers(tblUrunler entity)
		{
			this.SendPropertyChanging();
			entity.tblMarkalar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStokDurum")]
	public partial class tblStokDurum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _UrunID;
		
		private string _LotSeriNo;
		
		private System.Nullable<int> _Adet;
		
		private string _Barkod;
		
		private EntityRef<tblUrunler> _tblUrunler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUrunIDChanging(System.Nullable<int> value);
    partial void OnUrunIDChanged();
    partial void OnLotSeriNoChanging(string value);
    partial void OnLotSeriNoChanged();
    partial void OnAdetChanging(System.Nullable<int> value);
    partial void OnAdetChanged();
    partial void OnBarkodChanging(string value);
    partial void OnBarkodChanged();
    #endregion
		
		public tblStokDurum()
		{
			this._tblUrunler = default(EntityRef<tblUrunler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
		public System.Nullable<int> UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					if (this._tblUrunler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LotSeriNo", DbType="NVarChar(30)")]
		public string LotSeriNo
		{
			get
			{
				return this._LotSeriNo;
			}
			set
			{
				if ((this._LotSeriNo != value))
				{
					this.OnLotSeriNoChanging(value);
					this.SendPropertyChanging();
					this._LotSeriNo = value;
					this.SendPropertyChanged("LotSeriNo");
					this.OnLotSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
		public System.Nullable<int> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barkod", DbType="NVarChar(30)")]
		public string Barkod
		{
			get
			{
				return this._Barkod;
			}
			set
			{
				if ((this._Barkod != value))
				{
					this.OnBarkodChanging(value);
					this.SendPropertyChanging();
					this._Barkod = value;
					this.SendPropertyChanged("Barkod");
					this.OnBarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUrunler_tblStokDurum", Storage="_tblUrunler", ThisKey="UrunID", OtherKey="ID", IsForeignKey=true)]
		public tblUrunler tblUrunler
		{
			get
			{
				return this._tblUrunler.Entity;
			}
			set
			{
				tblUrunler previousValue = this._tblUrunler.Entity;
				if (((previousValue != value) 
							|| (this._tblUrunler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUrunler.Entity = null;
						previousValue.tblStokDurums.Remove(this);
					}
					this._tblUrunler.Entity = value;
					if ((value != null))
					{
						value.tblStokDurums.Add(this);
						this._UrunID = value.ID;
					}
					else
					{
						this._UrunID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUrunler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStokGirisAlt")]
	public partial class tblStokGirisAlt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _StokGirisNo;
		
		private System.Nullable<int> _UrunID;
		
		private string _LotSeriNo;
		
		private System.Nullable<int> _Adet;
		
		private EntityRef<tblUrunler> _tblUrunler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStokGirisNoChanging(System.Nullable<int> value);
    partial void OnStokGirisNoChanged();
    partial void OnUrunIDChanging(System.Nullable<int> value);
    partial void OnUrunIDChanged();
    partial void OnLotSeriNoChanging(string value);
    partial void OnLotSeriNoChanged();
    partial void OnAdetChanging(System.Nullable<int> value);
    partial void OnAdetChanged();
    #endregion
		
		public tblStokGirisAlt()
		{
			this._tblUrunler = default(EntityRef<tblUrunler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokGirisNo", DbType="Int")]
		public System.Nullable<int> StokGirisNo
		{
			get
			{
				return this._StokGirisNo;
			}
			set
			{
				if ((this._StokGirisNo != value))
				{
					this.OnStokGirisNoChanging(value);
					this.SendPropertyChanging();
					this._StokGirisNo = value;
					this.SendPropertyChanged("StokGirisNo");
					this.OnStokGirisNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
		public System.Nullable<int> UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					if (this._tblUrunler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LotSeriNo", DbType="NVarChar(30)")]
		public string LotSeriNo
		{
			get
			{
				return this._LotSeriNo;
			}
			set
			{
				if ((this._LotSeriNo != value))
				{
					this.OnLotSeriNoChanging(value);
					this.SendPropertyChanging();
					this._LotSeriNo = value;
					this.SendPropertyChanged("LotSeriNo");
					this.OnLotSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
		public System.Nullable<int> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUrunler_tblStokGirisAlt", Storage="_tblUrunler", ThisKey="UrunID", OtherKey="ID", IsForeignKey=true)]
		public tblUrunler tblUrunler
		{
			get
			{
				return this._tblUrunler.Entity;
			}
			set
			{
				tblUrunler previousValue = this._tblUrunler.Entity;
				if (((previousValue != value) 
							|| (this._tblUrunler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUrunler.Entity = null;
						previousValue.tblStokGirisAlts.Remove(this);
					}
					this._tblUrunler.Entity = value;
					if ((value != null))
					{
						value.tblStokGirisAlts.Add(this);
						this._UrunID = value.ID;
					}
					else
					{
						this._UrunID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUrunler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStokGirisUst")]
	public partial class tblStokGirisUst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _StokGNo;
		
		private System.Nullable<int> _FirmaID;
		
		private System.Nullable<System.DateTime> _ATarih;
		
		private string _StokAciklama;
		
		private EntityRef<tblFirma> _tblFirma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStokGNoChanging(System.Nullable<int> value);
    partial void OnStokGNoChanged();
    partial void OnFirmaIDChanging(System.Nullable<int> value);
    partial void OnFirmaIDChanged();
    partial void OnATarihChanging(System.Nullable<System.DateTime> value);
    partial void OnATarihChanged();
    partial void OnStokAciklamaChanging(string value);
    partial void OnStokAciklamaChanged();
    #endregion
		
		public tblStokGirisUst()
		{
			this._tblFirma = default(EntityRef<tblFirma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokGNo", DbType="Int")]
		public System.Nullable<int> StokGNo
		{
			get
			{
				return this._StokGNo;
			}
			set
			{
				if ((this._StokGNo != value))
				{
					this.OnStokGNoChanging(value);
					this.SendPropertyChanging();
					this._StokGNo = value;
					this.SendPropertyChanged("StokGNo");
					this.OnStokGNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaID", DbType="Int")]
		public System.Nullable<int> FirmaID
		{
			get
			{
				return this._FirmaID;
			}
			set
			{
				if ((this._FirmaID != value))
				{
					if (this._tblFirma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFirmaIDChanging(value);
					this.SendPropertyChanging();
					this._FirmaID = value;
					this.SendPropertyChanged("FirmaID");
					this.OnFirmaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> ATarih
		{
			get
			{
				return this._ATarih;
			}
			set
			{
				if ((this._ATarih != value))
				{
					this.OnATarihChanging(value);
					this.SendPropertyChanging();
					this._ATarih = value;
					this.SendPropertyChanged("ATarih");
					this.OnATarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAciklama", DbType="NVarChar(350)")]
		public string StokAciklama
		{
			get
			{
				return this._StokAciklama;
			}
			set
			{
				if ((this._StokAciklama != value))
				{
					this.OnStokAciklamaChanging(value);
					this.SendPropertyChanging();
					this._StokAciklama = value;
					this.SendPropertyChanged("StokAciklama");
					this.OnStokAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFirma_tblStokGirisUst", Storage="_tblFirma", ThisKey="FirmaID", OtherKey="ID", IsForeignKey=true)]
		public tblFirma tblFirma
		{
			get
			{
				return this._tblFirma.Entity;
			}
			set
			{
				tblFirma previousValue = this._tblFirma.Entity;
				if (((previousValue != value) 
							|| (this._tblFirma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblFirma.Entity = null;
						previousValue.tblStokGirisUsts.Remove(this);
					}
					this._tblFirma.Entity = value;
					if ((value != null))
					{
						value.tblStokGirisUsts.Add(this);
						this._FirmaID = value.ID;
					}
					else
					{
						this._FirmaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblFirma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSiparisUst")]
	public partial class tblSiparisUst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _SiparisNo;
		
		private System.Nullable<int> _FirmaID;
		
		private System.Nullable<System.DateTime> _ATarih;
		
		private string _SiparisAciklama;
		
		private EntityRef<tblFirma> _tblFirma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSiparisNoChanging(System.Nullable<int> value);
    partial void OnSiparisNoChanged();
    partial void OnFirmaIDChanging(System.Nullable<int> value);
    partial void OnFirmaIDChanged();
    partial void OnATarihChanging(System.Nullable<System.DateTime> value);
    partial void OnATarihChanged();
    partial void OnSiparisAciklamaChanging(string value);
    partial void OnSiparisAciklamaChanged();
    #endregion
		
		public tblSiparisUst()
		{
			this._tblFirma = default(EntityRef<tblFirma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiparisNo", DbType="Int")]
		public System.Nullable<int> SiparisNo
		{
			get
			{
				return this._SiparisNo;
			}
			set
			{
				if ((this._SiparisNo != value))
				{
					this.OnSiparisNoChanging(value);
					this.SendPropertyChanging();
					this._SiparisNo = value;
					this.SendPropertyChanged("SiparisNo");
					this.OnSiparisNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaID", DbType="Int")]
		public System.Nullable<int> FirmaID
		{
			get
			{
				return this._FirmaID;
			}
			set
			{
				if ((this._FirmaID != value))
				{
					if (this._tblFirma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFirmaIDChanging(value);
					this.SendPropertyChanging();
					this._FirmaID = value;
					this.SendPropertyChanged("FirmaID");
					this.OnFirmaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> ATarih
		{
			get
			{
				return this._ATarih;
			}
			set
			{
				if ((this._ATarih != value))
				{
					this.OnATarihChanging(value);
					this.SendPropertyChanging();
					this._ATarih = value;
					this.SendPropertyChanged("ATarih");
					this.OnATarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiparisAciklama", DbType="NVarChar(350)")]
		public string SiparisAciklama
		{
			get
			{
				return this._SiparisAciklama;
			}
			set
			{
				if ((this._SiparisAciklama != value))
				{
					this.OnSiparisAciklamaChanging(value);
					this.SendPropertyChanging();
					this._SiparisAciklama = value;
					this.SendPropertyChanged("SiparisAciklama");
					this.OnSiparisAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFirma_tblSiparisUst", Storage="_tblFirma", ThisKey="FirmaID", OtherKey="ID", IsForeignKey=true)]
		public tblFirma tblFirma
		{
			get
			{
				return this._tblFirma.Entity;
			}
			set
			{
				tblFirma previousValue = this._tblFirma.Entity;
				if (((previousValue != value) 
							|| (this._tblFirma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblFirma.Entity = null;
						previousValue.tblSiparisUsts.Remove(this);
					}
					this._tblFirma.Entity = value;
					if ((value != null))
					{
						value.tblSiparisUsts.Add(this);
						this._FirmaID = value.ID;
					}
					else
					{
						this._FirmaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblFirma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwStokGiris")]
	public partial class vwStokGiri
	{
		
		private System.Nullable<int> _StokGNo;
		
		private System.Nullable<System.DateTime> _ATarih;
		
		private string _StokAciklama;
		
		private string _LotSeriNo;
		
		private System.Nullable<int> _Adet;
		
		private string _FirmaAdi;
		
		private string _UrunAdi;
		
		public vwStokGiri()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokGNo", DbType="Int")]
		public System.Nullable<int> StokGNo
		{
			get
			{
				return this._StokGNo;
			}
			set
			{
				if ((this._StokGNo != value))
				{
					this._StokGNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> ATarih
		{
			get
			{
				return this._ATarih;
			}
			set
			{
				if ((this._ATarih != value))
				{
					this._ATarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAciklama", DbType="NVarChar(350)")]
		public string StokAciklama
		{
			get
			{
				return this._StokAciklama;
			}
			set
			{
				if ((this._StokAciklama != value))
				{
					this._StokAciklama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LotSeriNo", DbType="NVarChar(30)")]
		public string LotSeriNo
		{
			get
			{
				return this._LotSeriNo;
			}
			set
			{
				if ((this._LotSeriNo != value))
				{
					this._LotSeriNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
		public System.Nullable<int> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this._Adet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdi", DbType="NVarChar(350)")]
		public string FirmaAdi
		{
			get
			{
				return this._FirmaAdi;
			}
			set
			{
				if ((this._FirmaAdi != value))
				{
					this._FirmaAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(100)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this._UrunAdi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwSiparisAl")]
	public partial class vwSiparisAl
	{
		
		private System.Nullable<int> _SiparisNo;
		
		private System.Nullable<System.DateTime> _ATarih;
		
		private System.Nullable<int> _Adet;
		
		private string _UrunAdi;
		
		private System.Nullable<int> _UrunKodu;
		
		private string _Adres;
		
		private string _FirmaAdi;
		
		private string _CariKod;
		
		private string _VergiD;
		
		private string _VergiN;
		
		public vwSiparisAl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiparisNo", DbType="Int")]
		public System.Nullable<int> SiparisNo
		{
			get
			{
				return this._SiparisNo;
			}
			set
			{
				if ((this._SiparisNo != value))
				{
					this._SiparisNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> ATarih
		{
			get
			{
				return this._ATarih;
			}
			set
			{
				if ((this._ATarih != value))
				{
					this._ATarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
		public System.Nullable<int> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this._Adet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(100)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this._UrunAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="Int")]
		public System.Nullable<int> UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this._UrunKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(450)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdi", DbType="NVarChar(350)")]
		public string FirmaAdi
		{
			get
			{
				return this._FirmaAdi;
			}
			set
			{
				if ((this._FirmaAdi != value))
				{
					this._FirmaAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariKod", DbType="NVarChar(50)")]
		public string CariKod
		{
			get
			{
				return this._CariKod;
			}
			set
			{
				if ((this._CariKod != value))
				{
					this._CariKod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiD", DbType="NVarChar(50)")]
		public string VergiD
		{
			get
			{
				return this._VergiD;
			}
			set
			{
				if ((this._VergiD != value))
				{
					this._VergiD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiN", DbType="NVarChar(20)")]
		public string VergiN
		{
			get
			{
				return this._VergiN;
			}
			set
			{
				if ((this._VergiN != value))
				{
					this._VergiN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSiparisAlt")]
	public partial class tblSiparisAlt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _SiparisNo;
		
		private System.Nullable<int> _UrunID;
		
		private string _LotSeriNo;
		
		private System.Nullable<int> _Adet;
		
		private EntityRef<tblUrunler> _tblUrunler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSiparisNoChanging(System.Nullable<int> value);
    partial void OnSiparisNoChanged();
    partial void OnUrunIDChanging(System.Nullable<int> value);
    partial void OnUrunIDChanged();
    partial void OnLotSeriNoChanging(string value);
    partial void OnLotSeriNoChanged();
    partial void OnAdetChanging(System.Nullable<int> value);
    partial void OnAdetChanged();
    #endregion
		
		public tblSiparisAlt()
		{
			this._tblUrunler = default(EntityRef<tblUrunler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiparisNo", DbType="Int")]
		public System.Nullable<int> SiparisNo
		{
			get
			{
				return this._SiparisNo;
			}
			set
			{
				if ((this._SiparisNo != value))
				{
					this.OnSiparisNoChanging(value);
					this.SendPropertyChanging();
					this._SiparisNo = value;
					this.SendPropertyChanged("SiparisNo");
					this.OnSiparisNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
		public System.Nullable<int> UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					if (this._tblUrunler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LotSeriNo", DbType="NVarChar(50)")]
		public string LotSeriNo
		{
			get
			{
				return this._LotSeriNo;
			}
			set
			{
				if ((this._LotSeriNo != value))
				{
					this.OnLotSeriNoChanging(value);
					this.SendPropertyChanging();
					this._LotSeriNo = value;
					this.SendPropertyChanged("LotSeriNo");
					this.OnLotSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
		public System.Nullable<int> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUrunler_tblSiparisAlt", Storage="_tblUrunler", ThisKey="UrunID", OtherKey="ID", IsForeignKey=true)]
		public tblUrunler tblUrunler
		{
			get
			{
				return this._tblUrunler.Entity;
			}
			set
			{
				tblUrunler previousValue = this._tblUrunler.Entity;
				if (((previousValue != value) 
							|| (this._tblUrunler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUrunler.Entity = null;
						previousValue.tblSiparisAlts.Remove(this);
					}
					this._tblUrunler.Entity = value;
					if ((value != null))
					{
						value.tblSiparisAlts.Add(this);
						this._UrunID = value.ID;
					}
					else
					{
						this._UrunID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUrunler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUrunler")]
	public partial class tblUrunler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _UrunKodu;
		
		private string _UrunAdi;
		
		private System.Data.Linq.Binary _Resim;
		
		private System.Nullable<int> _KategoriID;
		
		private System.Nullable<int> _MarkaID;
		
		private string _Mensei;
		
		private string _Acıklama;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<int> _UpdateUser;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private EntitySet<tblStokDurum> _tblStokDurums;
		
		private EntitySet<tblStokGirisAlt> _tblStokGirisAlts;
		
		private EntitySet<tblSiparisAlt> _tblSiparisAlts;
		
		private EntityRef<tblKategoriler> _tblKategoriler;
		
		private EntityRef<tblMarkalar> _tblMarkalar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUrunKoduChanging(System.Nullable<int> value);
    partial void OnUrunKoduChanged();
    partial void OnUrunAdiChanging(string value);
    partial void OnUrunAdiChanged();
    partial void OnResimChanging(System.Data.Linq.Binary value);
    partial void OnResimChanged();
    partial void OnKategoriIDChanging(System.Nullable<int> value);
    partial void OnKategoriIDChanged();
    partial void OnMarkaIDChanging(System.Nullable<int> value);
    partial void OnMarkaIDChanged();
    partial void OnMenseiChanging(string value);
    partial void OnMenseiChanged();
    partial void OnAcıklamaChanging(string value);
    partial void OnAcıklamaChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnUpdateUserChanging(System.Nullable<int> value);
    partial void OnUpdateUserChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    #endregion
		
		public tblUrunler()
		{
			this._tblStokDurums = new EntitySet<tblStokDurum>(new Action<tblStokDurum>(this.attach_tblStokDurums), new Action<tblStokDurum>(this.detach_tblStokDurums));
			this._tblStokGirisAlts = new EntitySet<tblStokGirisAlt>(new Action<tblStokGirisAlt>(this.attach_tblStokGirisAlts), new Action<tblStokGirisAlt>(this.detach_tblStokGirisAlts));
			this._tblSiparisAlts = new EntitySet<tblSiparisAlt>(new Action<tblSiparisAlt>(this.attach_tblSiparisAlts), new Action<tblSiparisAlt>(this.detach_tblSiparisAlts));
			this._tblKategoriler = default(EntityRef<tblKategoriler>);
			this._tblMarkalar = default(EntityRef<tblMarkalar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="Int")]
		public System.Nullable<int> UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(100)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this.OnUrunAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunAdi = value;
					this.SendPropertyChanged("UrunAdi");
					this.OnUrunAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", DbType="Int")]
		public System.Nullable<int> KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					if (this._tblKategoriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaID", DbType="Int")]
		public System.Nullable<int> MarkaID
		{
			get
			{
				return this._MarkaID;
			}
			set
			{
				if ((this._MarkaID != value))
				{
					if (this._tblMarkalar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarkaIDChanging(value);
					this.SendPropertyChanging();
					this._MarkaID = value;
					this.SendPropertyChanged("MarkaID");
					this.OnMarkaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensei", DbType="NVarChar(20)")]
		public string Mensei
		{
			get
			{
				return this._Mensei;
			}
			set
			{
				if ((this._Mensei != value))
				{
					this.OnMenseiChanging(value);
					this.SendPropertyChanging();
					this._Mensei = value;
					this.SendPropertyChanged("Mensei");
					this.OnMenseiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acıklama", DbType="NVarChar(250)")]
		public string Acıklama
		{
			get
			{
				return this._Acıklama;
			}
			set
			{
				if ((this._Acıklama != value))
				{
					this.OnAcıklamaChanging(value);
					this.SendPropertyChanging();
					this._Acıklama = value;
					this.SendPropertyChanged("Acıklama");
					this.OnAcıklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUser", DbType="Int")]
		public System.Nullable<int> UpdateUser
		{
			get
			{
				return this._UpdateUser;
			}
			set
			{
				if ((this._UpdateUser != value))
				{
					this.OnUpdateUserChanging(value);
					this.SendPropertyChanging();
					this._UpdateUser = value;
					this.SendPropertyChanged("UpdateUser");
					this.OnUpdateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUrunler_tblStokDurum", Storage="_tblStokDurums", ThisKey="ID", OtherKey="UrunID")]
		public EntitySet<tblStokDurum> tblStokDurums
		{
			get
			{
				return this._tblStokDurums;
			}
			set
			{
				this._tblStokDurums.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUrunler_tblStokGirisAlt", Storage="_tblStokGirisAlts", ThisKey="ID", OtherKey="UrunID")]
		public EntitySet<tblStokGirisAlt> tblStokGirisAlts
		{
			get
			{
				return this._tblStokGirisAlts;
			}
			set
			{
				this._tblStokGirisAlts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUrunler_tblSiparisAlt", Storage="_tblSiparisAlts", ThisKey="ID", OtherKey="UrunID")]
		public EntitySet<tblSiparisAlt> tblSiparisAlts
		{
			get
			{
				return this._tblSiparisAlts;
			}
			set
			{
				this._tblSiparisAlts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKategoriler_tblUrunler", Storage="_tblKategoriler", ThisKey="KategoriID", OtherKey="ID", IsForeignKey=true, DeleteRule="SET DEFAULT")]
		public tblKategoriler tblKategoriler
		{
			get
			{
				return this._tblKategoriler.Entity;
			}
			set
			{
				tblKategoriler previousValue = this._tblKategoriler.Entity;
				if (((previousValue != value) 
							|| (this._tblKategoriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKategoriler.Entity = null;
						previousValue.tblUrunlers.Remove(this);
					}
					this._tblKategoriler.Entity = value;
					if ((value != null))
					{
						value.tblUrunlers.Add(this);
						this._KategoriID = value.ID;
					}
					else
					{
						this._KategoriID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblKategoriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMarkalar_tblUrunler", Storage="_tblMarkalar", ThisKey="MarkaID", OtherKey="ID", IsForeignKey=true, DeleteRule="SET DEFAULT")]
		public tblMarkalar tblMarkalar
		{
			get
			{
				return this._tblMarkalar.Entity;
			}
			set
			{
				tblMarkalar previousValue = this._tblMarkalar.Entity;
				if (((previousValue != value) 
							|| (this._tblMarkalar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMarkalar.Entity = null;
						previousValue.tblUrunlers.Remove(this);
					}
					this._tblMarkalar.Entity = value;
					if ((value != null))
					{
						value.tblUrunlers.Add(this);
						this._MarkaID = value.ID;
					}
					else
					{
						this._MarkaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblMarkalar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblStokDurums(tblStokDurum entity)
		{
			this.SendPropertyChanging();
			entity.tblUrunler = this;
		}
		
		private void detach_tblStokDurums(tblStokDurum entity)
		{
			this.SendPropertyChanging();
			entity.tblUrunler = null;
		}
		
		private void attach_tblStokGirisAlts(tblStokGirisAlt entity)
		{
			this.SendPropertyChanging();
			entity.tblUrunler = this;
		}
		
		private void detach_tblStokGirisAlts(tblStokGirisAlt entity)
		{
			this.SendPropertyChanging();
			entity.tblUrunler = null;
		}
		
		private void attach_tblSiparisAlts(tblSiparisAlt entity)
		{
			this.SendPropertyChanging();
			entity.tblUrunler = this;
		}
		
		private void detach_tblSiparisAlts(tblSiparisAlt entity)
		{
			this.SendPropertyChanging();
			entity.tblUrunler = null;
		}
	}
}
#pragma warning restore 1591
